version: "3"
services:
  web:
    image: bmonteiro00/keycash:v0.0.3
    deploy:
      replicas: 10 
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet:
